"""Capture the existing public Kim-vocals session before changing its pipeline.

This is a port-pipeline baseline, separate from the pristine upstream model
fixture generated by generate_original_kim_golden.py. The input crosses the
default 352,800-sample chunk boundary and records both written stems.
"""
from __future__ import annotations

import json
from pathlib import Path
import tempfile

import numpy as np
import soundfile as sf
import torch

from mel_band_roformer.clean_api import MelBandRoformerSession


def main() -> None:
    if not torch.cuda.is_available():
        raise RuntimeError("Kim-vocals public baseline requires CUDA")
    sample_rate = 44100
    length = sample_rate * 9
    time = np.arange(length, dtype=np.float64) / sample_rate
    left = (0.2 * np.sin(2 * np.pi * 220 * time)
            + 0.04 * np.sin(2 * np.pi * 70 * time)) * np.exp(-0.12 * time)
    right = (0.15 * np.sin(2 * np.pi * 330 * time)
             + 0.03 * np.sin(2 * np.pi * 95 * time)) * np.exp(-0.1 * time)
    waveform = np.stack([left, right], axis=-1).astype(np.float32)
    torch.set_num_threads(1)
    torch.manual_seed(12345)
    with tempfile.TemporaryDirectory() as location:
        root = Path(location)
        inputs = root / "inputs"
        outputs = root / "outputs"
        inputs.mkdir()
        sf.write(inputs / "synthetic.wav", waveform, sample_rate, subtype="FLOAT")
        with MelBandRoformerSession(device="cuda:0", progress=False) as session:
            written = session.infer(inputs, store_dir=outputs, output_format="wav_float32")
        stems = {}
        for entry in written:
            audio, rate = sf.read(entry["output_path"], dtype="float32", always_2d=True)
            if rate != sample_rate:
                raise AssertionError(f"Unexpected rate: {rate}")
            stems[entry["output_id"]] = audio
        if set(stems) != {"vocals", "instrumental"}:
            raise AssertionError(f"Unexpected stem names: {set(stems)}")
        for name, audio in stems.items():
            if audio.shape != waveform.shape or not np.isfinite(audio).all():
                raise AssertionError(f"Invalid {name} output: {audio.shape}")

    fixtures = Path(__file__).resolve().parents[1] / "tests/fixtures/original_kim_golden"
    np.savez_compressed(fixtures / "nine_seconds_public.npz", waveform=waveform,
                        vocals=stems["vocals"], instrumental=stems["instrumental"])
    manifest_file = fixtures / "manifest.json"
    manifest = json.loads(manifest_file.read_text())
    manifest["public_baseline"] = {
        "kind": "existing port session, not upstream inference wrapper",
        "input_shape": list(waveform.shape),
        "output_ids": sorted(stems),
        "output_shape": list(stems["vocals"].shape),
        "sample_rate": sample_rate,
        "torch": torch.__version__,
        "cuda_device": torch.cuda.get_device_name(0),
    }
    manifest_file.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"Captured {sorted(stems)}: {waveform.shape}")


if __name__ == "__main__":
    main()
